### ISSUE TITLE
Deprecation log detection

### ISSUE THREAD

**Issue by cachedout** [elastic/e2e-testing#1872]
## Background

One need that is emerging is the need to collect certain types of logs from testing and then analyze them in order to detect certain conditions. One of the conditions that we need to detect somewhat urgently is whether or not the E2E tests produce any deprecation warnings in Elasticsearch.

## Tasks

- [ ] Modify the test suite so that Elasticsearch logs are preserved at the end of the test run for analysis.
- [ ] Ensure that Elasticsearch is [logging at a sufficient level](https://www.elastic.co/guide/en/elasticsearch/reference/current/logging.html) to detect when a deprecated endpoint is accessed . 
- [ ] Modify the Jenkins pipelines if necessary to ensure that the produced logs are collected and made available as an artifact.

## Possible future work

* Modify the test suite so that after each test is run, we check for deprecation entries so that we can correlate a specific test with the generation of a specific set of deprecation log entries.

**Comment by kuisathaverat** [comment]
obsolete
