### ISSUE TITLE
Bring back docker support

### ISSUE THREAD

**Issue by mdelapenya** [elastic/e2e-testing#1998]
We could create a Git branch right before the commit adding VM support, so that teams are able to use the test framework with docker support, which means installing the elastic-agent in Centos and Debian containers, and Windows machines. 
 Using Docker has the nuance that certain limitations apply, for instance not being able to use Elastic Endpoint in tests, we need not fix this but rather can just ignore its usage and results when in Docker environment.  Are there other features we know and want to list out?

To accomplish this:
- We could backport only the fixes that are present in `main` to that branch.
- We could delegate to mergify the backports creating a specific Github label so that mergify performs the backport to that label in an automated manner.

### Tasks:
- [ ] create a `v1-docker` branch
- [ ] create Github label for backports to docker
- [ ] enable mergify to backport to the new branch using the new label

### List of commits to use
<img width="772" alt="Screenshot 2022-01-12 at 19 34 38" src="https://user-images.githubusercontent.com/951580/149203097-42fb214d-b06e-49fb-ba19-727c02472b69.png">

cc/ @EricDavisX @jlind23 @elastic/observablt-robots

**Comment by cachedout** [comment]
> We could create a Git branch right before the commit adding VM support, so that teams are able to use the test framework with docker support, which means installing the elastic-agent in Centos and Debian containers, and Windows machines.

@mdelapenya Could you please talk about more about the reasons this is beneficial? Is this simply to re-enable the ability to run E2E tests locally or is there some other benefit I'm missing?

**Comment by mdelapenya** [comment]
Exactly, the main benefit would be developers running tests locally in containers that run in the local machine.

After talking to you offline, we could also create a dedicated test suite that supports running in Docker, as the stand-alone-mode scenarios, so that we are able to run a subset of them locally.

**Comment by mdelapenya** [comment]
After having a robust build system, I'd advocate to close this issue, as it's totally possible to reproduce any supported OS with only having access to the AWS account
